### ISSUE TITLE
Missing categories, e.g. Broken links under "Get help"

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#1]
Dear Peter,

on the main page, the links under 'Get help':
-Documentation on this wiki ([http://biopython.github.io/wiki/:Category:Wiki_Documentation])
-Cookbook (working examples) ([(http://biopython.github.io/wiki/:Category:Cookbook])

don't work.

**Comment by peterjc** [comment]
Ah - fall out from the current way I (didn't) deal with categories at all:

https://github.com/peterjc/mediawiki_to_git_md/issues/6

Yes, this is a major problem.

**Comment by peterjc** [comment]
Progress, the pages now exist - although without the automatic links to all the pages tagged with that category:

https://github.com/biopython/biopython.github.io/blob/master/wiki/Category:Wiki_Documentation.md

However, the URLs to them are not right, e.g. http://biopython.github.io/wiki/:Category:Wiki_Documentation should be http://biopython.github.io/wiki/Category:Wiki_Documentation without the extra leading colon.

**Comment by peterjc** [comment]
The category pages now exist, links to them work (colons dealt with pending an update to pandoc itself), and pages in a category now have a matching Jekyll tag in their header. Still to do - automatically include a listing of all the pages with the matching tag.

**Comment by peterjc** [comment]
This is now working, fixes for https://github.com/peterjc/mediawiki_to_git_md/issues/6 mean we now assign the special ``Category:XXX`` wiki pages to a different layout template (currently ``_layout/tagpage.html`` in line with relevant examples online) with some Jekyll liquid templating magic to include all the pages with tag ``XXX``.
