### ISSUE TITLE
Old Biopython logo competition submissions

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#100]
In the [BOSC 2003](http://biopython.org/DIST/docs/presentations/bosc_biopython.pdf) talk I found these logos on the first slide: 

![bosc_biopython-1](https://cloud.githubusercontent.com/assets/4503120/18316034/67e6465e-7519-11e6-84cb-20e640c34ff1.png)

Are these the entries from the 2003 logo competition? If yes, this slide may be used to update the Logo.md page?

**Comment by peterjc** [comment]
I believe so, yes, but it was before I was involved. @idoerg might be able to comment as from memory he was de facto project lead around that time?

There is also a chance the OBF has a backup of the original files which were at one point on an OBF web-server...

**Comment by idoerg** [comment]
Yes, those logos were suggested designs by biopythoneers and their associates then. The bottom right was my design, thankfully not accepted.

**Comment by peterjc** [comment]
Some of these survive as attachments from the mailing list archive, e.g.

http://mailman.open-bio.org/pipermail/biopython/2003-May/001314.html
http://mailman.open-bio.org/pipermail/biopython/attachments/20030521/2ed4f971/biopythonlogo2-0001.png

http://mailman.open-bio.org/pipermail/biopython/2003-May/001321.html
http://mailman.open-bio.org/pipermail/biopython/attachments/20030521/fde7b134/biopythonlogo4-0001.png

However most of the submissions were via short-lived personal home pages which now Error 404.

Here's the result announcement email from Jeff Chang:
http://mailman.open-bio.org/pipermail/biopython/2003-July/001478.html

Using the image from the BOSC 2003 talk seems fine to me :)
