### ISSUE TITLE
SeqIO - parsing UniProt-XML throws error

### ISSUE THREAD

**Issue by hellingerbioinf** [biopython/biopython.github.io#109]
## Error Description
Parsing UniProt-XML throws an error because apparently SeqIO cannot handle recently changed tags. `<begin status="unknown"/>` as well as `<end status="unknown"/>` appear to be the culprits.

### File:
[ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz](url)

### Code:
```python
#!/usr/bin/python

import sys
import gzip
from Bio import SeqIO

filename='uniprot_sprot.xml.gz'

sys.stderr.write("Reading %s..." % filename)
with gzip.open(filename) as infile:
  for entry in SeqIO.parse(infile, "uniprot-xml"):
    print entry.id
```

## Workaround
In the meantime it is possible to correct the faulty tags by sed-substitutions as a **temporary workaround**:
`zcat uniprot_sprot.xml.gz | sed 's/<begin status="unknown"\/>/<begin position="1"\/>/' | sed 's/<end status="unknown"\/>/<end position="1"\/>/' > uniprot_sprot.workaround.xml`

**Comment by peterjc** [comment]
This is not a problem on the website, so could you file this bug on the Biopython code repository: instead please? https://github.com/biopython/biopython/issues

(If not, I'll try to remember to file the issue on your behalf later).

Also if you can find any details in the recent UniProt release notices about this change, that would be very helpful.

Thanks!

**Comment by hellingerbioinf** [comment]
Sry for posting in the wrong section! I now filed the bug on the code repository (#1004).
Unfortunately, I couldn't find any helpful information in the release notes about those changes.
Will report back if I do!

**Comment by peterjc** [comment]
Thanks - let's continue this on https://github.com/biopython/biopython/issues/1004
