### ISSUE TITLE
Styling: Adjust page width for wide examples?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#11]
e.g. http://biopython.org/wiki/AlignIO needs more width

**Comment by MarkusPiotrowski** [comment]
You can add a horizontal scrollbar, which only appears if the text is too long:
In <code>poole.css</code> find the <code>.highlight</code> element (line 183) and add the following two lines:

    white-space: pre;
    overflow-x: auto;

<code>white-space: pre</code> prevents the line break and <code>overflow-x: auto</code> adds the scrollbar when it is needed.
I think that is a clean solution, no need to adjust the width of individual pages or code boxes.
  
![h-scrollbar](https://cloud.githubusercontent.com/assets/4503120/14507926/4ef1c35c-01c5-11e6-9454-1ea7fafa0566.png)

**Comment by peterjc** [comment]
That looks and sounds good - can you do this as a pull request later in the week (after what should be the final re-import and history-rewrite to take care of a few name mappings #2 and some Python code block rendering). Thanks!

**Comment by peterjc** [comment]
Closed by PR #23, thank you.
