### ISSUE TITLE
Bio.Medline.parse

### ISSUE THREAD

**Issue by wangxj524** [biopython/biopython.github.io#115]
In Bio.Medline.parse function:
# These keys point to string values
    textkeys = ("ID", "PMID", "SO", "RF", "NI", "JC", "TA", "IS", "CY", "TT",
                "CA", "IP", "VI", "DP", "YR", "PG", "LID", "DA", "LR", "OWN",
                "STAT", "DCOM", "PUBM", "DEP", "PL", "JID", "SB", "PMC",
                "EDAT", "MHDA", "PST", "AB", "AD", "EA", "TI", "JT")
Sometimes, there are many ADs in one record. Why convert AD as a string value?

**Comment by peterjc** [comment]
This issue tracker is for problems with our website, for problems/suggestions with Biopython itself please file your issue at https://github.com/biopython/biopython/issues

In this case the ``AD`` line is an address, and in the example in our test cases passing it as one long string looks correct: https://github.com/biopython/biopython/blob/biopython-169/Tests/Medline/pubmed_result2.txt#L29
