### ISSUE TITLE
Publication entries

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#12]
e.g. http://biopython.org/wiki/Documentation.html and http://biopython.org/wiki/Publications used a PubMed plugin under MediaWiki

**Comment by peterjc** [comment]
There are too many entries on https://github.com/biopython/biopython.github.io/blob/master/wiki/Publications.md to do by hand, but there is likely some script already out there to go from a PubMed ID to a markdown formatted citation with link. You might be able to do this with Biopython itself with the MedLine parser?

**Comment by peterjc** [comment]
Another idea: You might be able to find/setup a MediaWiki instance with a suitable plugin installed (i.e. http://mjambon.com/biblio_php.html or https://www.mediawiki.org/wiki/Extension:BiblioPlus instead), copy and paste the old page into MediaWiki, and get back the citation rendered as HTML (even just as an edit preview), which you can turn into Markdown with pandoc.

We still have the original MarkDown version of this page in the git history, see https://raw.githubusercontent.com/biopython/biopython.github.io/869e580636156b38cdf406def3e630bfad086393/wiki/Publications.mediawiki

Here the entries looked like this:

```
<biblio>
#ArmanoAndManconi2009 pmid=19799773
// Used Bio.PDB
#BanachEtAl2009 pmid=19399224
// Used Bio.PDB and Bio.KDTree
...
</biblio>
```

However, pandoc didn't change much, this is how they look now in Markdown:

```
<biblio>

1.  ArmanoAndManconi2009 pmid=19799773

// Used Bio.PDB

1.  BanachEtAl2009 pmid=19399224

// Used Bio.PDB and Bio.KDTree

...
</biblio>
```

**Comment by MarkusPiotrowski** [comment]
I have written a script which takes a PubMed identifier and prints a numbered, well formatted reference as markdown, ready for copy & paste. You find the script as [gist pmid_to_markdown_ref.py](https://gist.github.com/MarkusPiotrowski/e3a6f4234378431243824c61385bd43d) 

Example:
```bash
Starting line number? 1
PubMed ID? ("x" for eXit, "r" to Reset line number): 19799773

1.  Armano G and Manconi A (2009) 
    ProDaMa: an open source Python library to generate protein structure datasets.
    [BMC Res Notes, 2, 202](http://dx.doi.org/10.1186/1756-0500-2-202)

PubMed ID? ("x" for eXit, "r" to Reset line number): 19399224

2.  Banach M, Stapor K and Roterman I (2009) 
    Chaperonin structure: the large multi-subunit protein complex.
    [Int J Mol Sci, 10, 844-61](http://dx.doi.org/10.3390/ijms10030844)

PubMed ID? ("x" for eXit, "r" to Reset line number): 19812729

3.  Thomson RC (2009) 
    PhyLIS: a simple GNU/Linux distribution for phylogenetics and phyloinformatics.
    [Evol. Bioinform. Online, 5, 91-5](http://www.ncbi.nlm.nih.gov/pubmed/?term=19812729)

PubMed ID? ("x" for eXit, "r" to Reset line number): r
Starting line number? 1
PubMed ID? ("x" for eXit, "r" to Reset line number): 18662398

1.  Antao T, Lopes A, Lopes RJ, Beja-Pereira A and Luikart G (2008) 
    LOSITAN: a workbench to detect molecular adaptation based on a Fst-outlier method.
    [BMC Bioinformatics, 9, 323](http://dx.doi.org/10.1186/1471-2105-9-323)

PubMed ID? ("x" for eXit, "r" to Reset line number): x
Goodbye!
>>> 
``` 
It would be great if we can put the script as another Cookbook example (for using `Bio.Entrez`) on the homepage. If OK I would write a new page and submit as pull request.

**Comment by peterjc** [comment]
As discussed by email, I think adding this script as a Cookbook entry is a good idea.
