### ISSUE TITLE
Webpage not rendering properly, just plain text

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#120]
I am reporting a problem with the Biopython website at http://biopython.org

My web browser is Firefox version 54.0.1 and Internet Explorer 11, running on operating system Win7 (64 bit).

Something went wrong with the last (?) commit, the web page (except the start page) does not render properly, it just displays plain text. Do you see the same?

**Comment by peterjc** [comment]
I see it too - most likely something on the CSS styles...

**Comment by peterjc** [comment]
Hmm, https://travis-ci.org/biopython/biopython.github.io/branches is happy (not a perfect recreation of the actual GitHub pages build, but close), and no one has touched the layout in months.

**Comment by peterjc** [comment]
It looks like the CSS relative links are broken, they should point at http://biopython.org/assets/css/poole.css etc.

For example, http://biopython.org/wiki/Documentation or http://biopython.org/wiki/Documentation.html now has:

```html
  <!-- CSS -->
  <link rel="stylesheet" href="assets/css/poole.css">
  <link rel="stylesheet" href="assets/css/syntax.css">
  <link rel="stylesheet" href="assets/css/hyde.css">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans%3A400,400italic,700%7CAbril+Fatface">
```

As a relative link, that means http://biopython.org/wiki/assets/css/poole.css which breaks.

My guess is GitHub updated something on Jekyll which broke our setup...

**Comment by MarkusPiotrowski** [comment]
Yes, I have an old version in my Github.io (https://markuspiotrowski.github.io/wiki/Documentation) and there the relative links have a leading backslash:


```
 <!-- CSS -->
  <link rel="stylesheet" href="/assets/css/poole.css">
  <link rel="stylesheet" href="/assets/css/syntax.css">
  <link rel="stylesheet" href="/assets/css/hyde.css">
```

**Comment by peterjc** [comment]
These are set in ``_includes/head.html`` as follows:

```html
  <!-- CSS -->
  <link rel="stylesheet" href="{{ site.baseurl }}assets/css/poole.css">
  <link rel="stylesheet" href="{{ site.baseurl }}assets/css/syntax.css">
  <link rel="stylesheet" href="{{ site.baseurl }}assets/css/hyde.css">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans%3A400,400italic,700%7CAbril+Fatface">
```

So something to do with ``site.baseurl`` looks to blame...

**Comment by peterjc** [comment]
Our ``_config.yml`` file has a sensible value here, not changed in 2 years:

```yaml
baseurl: /
```

**Comment by peterjc** [comment]
Possibly related https://github.com/jekyll/jekyll/issues/4711 - need to read up more on this

**Comment by peterjc** [comment]
Something changed with ``baseurl`` in https://jekyllrb.com/news/2017/07/17/jekyll-3-5-1-released/

**Comment by peterjc** [comment]
According to https://pages.github.com/versions/ currently they use:


Dependency | Version
-- | --
jekyll | 3.4.5
activesupport | 4.2.8
github-pages-health-check | 1.3.4
github-pages | 145
html-pipeline | 2.6.0
jekyll-avatar | 0.4.2
jekyll-coffeescript | 1.0.1
jekyll-default-layout | 0.1.4
jekyll-feed | 0.9.2
jekyll-gist | 1.4.0
jekyll-github-metadata | 2.5.1
jekyll-mentions | 1.2.0
jekyll-optional-front-matter | 0.2.0
jekyll-paginate | 1.1.0
jekyll-readme-index | 0.1.0
jekyll-redirect-from | 0.12.1
jekyll-relative-links | 0.4.1
jekyll-sass-converter | 1.5.0
jekyll-seo-tag | 2.2.3
jekyll-sitemap | 1.0.0
jekyll-swiss | 0.4.0
jekyll-theme-architect | 0.0.4
jekyll-theme-cayman | 0.0.4
jekyll-theme-dinky | 0.0.4
jekyll-theme-hacker | 0.0.4
jekyll-theme-leap-day | 0.0.4
jekyll-theme-merlot | 0.0.4
jekyll-theme-midnight | 0.0.4
jekyll-theme-minimal | 0.0.4
jekyll-theme-modernist | 0.0.4
jekyll-theme-primer | 0.3.1
jekyll-theme-slate | 0.0.4
jekyll-theme-tactile | 0.0.4
jekyll-theme-time-machine | 0.0.4
jekyll-titles-from-headings | 0.2.0
jemoji | 0.8.0
kramdown | 1.13.2
liquid | 3.0.6
listen | 3.0.6
minima | 2.1.1
nokogiri | 1.7.2
rouge | 1.11.1
ruby | 2.4.0
safe_yaml | 1.0.4
sass | 3.5.1

At some point we can try updating Ruby and activesupport on TravisCI at some point for sanity testing.

According to https://jekyllrb.com/docs/history/#v3-4-5 there have been some ``baseurl`` changes in the v3.4.x series..

**Comment by peterjc** [comment]
There's also text "*Source of biopython.org website, migrated from MediaWiki*" on the top of the sidebar, which is the GitHub repository's caption.

**Comment by peterjc** [comment]
I've "fixed" this with brute force, hard coding the ``/`` in place of ``site.baseurl``, which is not elegant but practical. I would welcome a better long term solution here...

**Comment by MarkusPiotrowski** [comment]
According to http://ben.balter.com/jekyll-style-guide/config/ ```site.baseurl``` should only be used if the whole project sits in one subfolder, e.g. ```...biopython.org\biopython```. Since this is not the case, encoding the full relative path (like done now) seems to be the correct/intended way to do it.

**Comment by peterjc** [comment]
At the early stages of the MediaWiki conversion I did consider having ``wiki/`` as a self contained GitHub Pages site, in which case the base URL would have been ``wiki/``. As is, having the base URL of ``/`` seems fine to me (and worked fine for some time), but I am likely not fully understanding the Jekyll team's intent.
