### ISSUE TITLE
Redirect landing page to main page

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#121]
Currently our ``index.md`` file says:

> We recently migrated from MediaWiki to GitHub pages, see our GitHub Pages Repository.
> 
> The new site is mostly working, but there are a number of known issues.
> 
> Continue to the main Wiki page.

We should probably redirect to the main wiki page now?

**Comment by MarkusPiotrowski** [comment]
Agree.

**Comment by peterjc** [comment]
I think the simplest way to do this is redirect to http://biopython.org/wiki/Biopython but there is value in doing the opposite and having the main page URL be just http://biopython.org/ ?
