### ISSUE TITLE
HTML anchors within pages not working?

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#13]
e.g. http://biopython.org/wiki/Documentation#Papers does not seem to scroll to the child section?

*Edit:* This link appears in http://biopython.org/wik/Publications aka https://github.com/biopython/biopython.github.io/blob/master/wiki/Publications.md from the original mediawiki text:

```
There is a separate shorter listing of [[Documentation#Papers|Biopython papers you may wish to cite]].
```

**Comment by MarkusPiotrowski** [comment]
In the html-document (that goes online) the anchor is lower case: ```<h4 id="papers"...```
So [http://biopython.org/wiki/Documentation#papers](http://biopython.org/wiki/Documentation#papers) does work.
Actually I wonder, where are the anchors in the markdown document? What's the magic behind this?

**Comment by peterjc** [comment]
It looks like MediaWiki requires the final URL follows some canonical title case rules, and likely does this internally when rendering the original text into HTML:

https://www.mediawiki.org/wiki/Help:Links#Internal_links <-- works
https://www.mediawiki.org/wiki/Help:Links#Internal_Links <-- fails

My guess is the Jekyll/kramdown stack has its own rules for the case of the automatic anchor names, which differ, and we may need to tweak the links to match? More investigation is needed.

**Comment by MarkusPiotrowski** [comment]
I have checked a few of them. Jekyll seem to make them all lower-case and hyphen instead of underscore, e.g. instead of 

`SeqIO#File_Formats`

this is the correct link:

`SeqIO#file-formats`

However, this seems to be a minor problem, there are approx. 8 internal links with anchors in 4 pages.

**Comment by peterjc** [comment]
OK, so we should just change the URLs to match the new anchors?

(We can't fix any external anchors, but at least such links will still go to the right page)

**Comment by MarkusPiotrowski** [comment]
Yes, I'm working on it.

**Comment by peterjc** [comment]
Closing this on the assumption pull request #68 resolved it, thanks Markus.
