### ISSUE TITLE
Enable HTTPS for website

### ISSUE THREAD

**Issue by hlapp** [biopython/biopython.github.io#133]
Through a partnership with Let's Encrypt [Github allows HTTPS for custom domains since May 1](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). I suggest enabling this here.

I have already made the necessary changes in DNS (see `dig biopython.org`).

You might need to trigger SSL cert issuance, see bioperl/bioperl.github.io#45.

**Comment by peterjc** [comment]
``CNAME`` setting files removed in https://github.com/biopython/biopython.github.io/commit/d66b2eeed078775b2843a65b2974a5dc5745089b and restored in https://github.com/biopython/biopython.github.io/commit/4ef48f3e69458ae65b0eb459f80b3a650dd474ae

**Comment by peterjc** [comment]
Working now - thank you Hilmar!

**Comment by peterjc** [comment]
I had just confirmed by hand that https://biopython.org worked.

I have now followed the instructions via https://help.github.com/articles/securing-your-github-pages-site-with-https/ and have ticked the automatically enforce HTTPS box now, thanks!
