### ISSUE TITLE
Styling: Edit this page buttons pointing at GitHub source .md file

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#14]
e.g. from http://biopython.org/wiki/GitUsage want an easy link back to https://github.com/biopython/biopython.github.io/blob/master/wiki/GitUsage.md from where the user can start editing (if they have a GitHub account etc).

**Comment by MarkusPiotrowski** [comment]
Do you want this for every page? Then we can probably implement this with a fixed head element like "Edit this page on GitHub [GitHub icon]", combined with a link using something like {{ site.name }}?
If you want to put this only selected pages, it is probably easiest to attach a linked GitHub icon to the first headline.

**Comment by peterjc** [comment]
I was thinking every page - probably some liquid template code putting ``https://github.com/biopython/biopython.github.io/blob/master/`` in front of the current page's relative path? i.e. Functionally a replacement for the Wiki's edit button.

Layout wise, perhaps in the footer - see also #20?

**Comment by MarkusPiotrowski** [comment]
Here in the header, how do you like this?

![edit-button](https://cloud.githubusercontent.com/assets/4503120/14545181/41f0dcb4-029d-11e6-9ee4-613f6d6f1996.png)

You can test it [here](http://markuspiotrowski.github.io/wiki/Biopython).

**Comment by peterjc** [comment]
Functionally that's exactly what I had in mind - that would certainly be a useful step forwards :+1:

Visually, I'm not sure it goes with the current template (the font size looks bigger than than the other text, and the underlining is unusual), but I'm open to polling the community for the overall site look anyway.

**Comment by MarkusPiotrowski** [comment]
I took the design from another template, without changing anything (since I'm not using Jekyll, I have to work and test online to see what I'm doing). The styling can be adjusted. At the moment the 'button' is fixed to the right of the page, maybe it's nicer to have it fixed to the right of the text.

**Comment by MarkusPiotrowski** [comment]
Would it be OK to anchor such button in the <code>default.html<code> template, or are there pages that shouldn't be included? I tried the <code>wiki.html</code> template, but there are (too) many Wiki pages that don't use this template.

**Comment by peterjc** [comment]
Right now the wiki pages use either wiki (most), page (the few which appear in the side bar) or tagpage (the old MediaWiki category pages). I suspect that the final "landing" page could end up being a uniquely styled page type...

Probably it would be fine to use the ``default.html`` template?

**Comment by peterjc** [comment]
See also http://ben.balter.com/2015/09/13/github-pages-edit-button/

**Comment by MarkusPiotrowski** [comment]
This is a very clear and simple version, just a right-top justified link with a thin horizontal bar. Like a header (left part may later be used for navigation, e.g. page title or path). Wiith the functionality described in http://ben.balter.com/2015/09/13/github-pages-edit-button/, e.g. the file is opened in editing mode in GitHub.

![untitled-1](https://cloud.githubusercontent.com/assets/4503120/15336172/8852ec3c-1c75-11e6-9cd2-c8623381d10f.png)

You can test it (temporarily) [here](http://markuspiotrowski.github.io/wiki/Documentation).

**Comment by peterjc** [comment]
Let's go with your new version for now?

**Comment by MarkusPiotrowski** [comment]
When you press the button you are directed to the Biopython web site respository, the file opens in **Edit** mode and you are advised that you don't have writing privilegs. So if you submit, this will open a branch on your local respository and you can do the pull request from there. If you are not logged in to GitHub you are directed to GitHub login page.

![untitled-1](https://cloud.githubusercontent.com/assets/4503120/15384945/6f994dc4-1d9e-11e6-8c64-e45b33b7fbba.png)

Thus I think we can close this issue.

**Comment by peterjc** [comment]
Perfect, thank you!

**Comment by peterjc** [comment]
Fixed with https://github.com/biopython/biopython.github.io/commit/a2b3c5bd551fbfe8b41192d4ae6660b4bb2a68bb
