### ISSUE TITLE
Styling: Use transparent Biopython logo

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#15]
Following discussion on #3, @widdowquinn has prepared some updated logo images currently at biopython/biopython#807 which could be used here for the website. This would allow the grey background to be changed more freely (currently matching the dark grey of the logo image).

Also the way I inserted the logo into the hyde template was not very elegant. That could be done better.

**Comment by MarkusPiotrowski** [comment]
Suggestion for two little changes to the sidebar:
1.  Transparent Biopython logo
2.  Put 'non-navigation' elements to the bottom of the sidebar

Before:
![untitled-1](https://cloud.githubusercontent.com/assets/4503120/15198053/400b9036-17d5-11e6-9ac3-14c9aa4b1139.png)

After:
![untitled-2](https://cloud.githubusercontent.com/assets/4503120/15198063/4c195f0c-17d5-11e6-917b-e253cfe7cc0d.png)

OK?

**Comment by peterjc** [comment]
Looks nice - I was meaning to grab the logo @widdowquinn prepared on https://github.com/biopython/biopython/pull/807 and add it to this repository instead (committing under his name), perhaps at the same time resolving #25.

**Comment by MarkusPiotrowski** [comment]
No problem, I think they are nearly identical (I guess Leighton and I have used the same template and deleted automatically the white background). 
However, can you downscale this to a width of ~600 px? In the sidebar, we need only about 200 px maximum, but as 'top'-bar it can be bigger.
You can temporarily check how it looks with @widdowquinn transparent logo (width: 600 px) here:
http://markuspiotrowski.github.io

**Comment by MarkusPiotrowski** [comment]
Here I adjusted the navigation for **mobiles**, having the links next to each other instead of one below the other. Also reduced the margins (in this view) to have more content. This touches slightly #26. 

![untitled-1](https://cloud.githubusercontent.com/assets/4503120/15249122/4c920980-191e-11e6-8e32-f75f2e2d73d7.png)

Again, this can be tested temporarily here: http://markuspiotrowski.github.io
@peterjc When the transparent logo is committed I would prepare a pull request

**Comment by peterjc** [comment]
That does work better for mobiles 👍

**Comment by MarkusPiotrowski** [comment]
Looks much better now!

**Comment by peterjc** [comment]
Great. We're now free to change the dark grey background colour now that the logo background is transparent.
