### ISSUE TITLE
"Home" link on sidebar or Biopython logo

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#16]
Can we put either a "Home" link on the sidebar or link the Biopython logo to <code>\wiki\Biopython</code>? If one jumps directly into some page (e.g. directed from a Google search) there is no way to find the starting page.

**Comment by peterjc** [comment]
Agreed, the logo replaced a big text "Biopython" link to the home page, and so the image should also link there. See also #15.

**Comment by peterjc** [comment]
I've got that change tested locally pending a final re-import from MediaWiki to update a few user mappings (#2) and some Python code markup...

**Comment by peterjc** [comment]
Done with recent re-writing of the git history.
