### ISSUE TITLE
the website is not showing properly, only plain text. please help..

### ISSUE THREAD

**Issue by souvikde99** [biopython/biopython.github.io#164]
I am reporting a problem with my website at https://souvikde99.github.io/souvik/

My web browser is XXX version XXX, running on operating system windows .10

(Please go to https://github.com/souvikde99/souvik to search for or
report any problems with Biopython itself.)
the website is not showing properly, only plain text. please help..
but it's working fine in offline mode. in my pc

**Comment by JoaoRodrigues** [comment]
This issue tracker is for problems related with the Biopython website - not for support for web developing your own pages. Sorry.
