### ISSUE TITLE
Outdated link of Sphinx on the website main page

### ISSUE THREAD

**Issue by Logan1x** [biopython/biopython.github.io#165]
I am reporting a problem with the Biopython website at http://biopython.org

My web browser is Firefox version 76.0.1, running on operating system manjaro.

If you click on the below link on the website,

![image](https://user-images.githubusercontent.com/10944610/87221810-873d4a00-c38c-11ea-9874-9c283e8ec447.png)

it says 

![image](https://user-images.githubusercontent.com/10944610/87221833-bfdd2380-c38c-11ea-9310-3d5c39abfce2.png)

The link has been changed from http://sphinx.pocoo.org/ to https://www.sphinx-doc.org/en/master/.

I would like to work on this issue, but I haven't worked with Jekyll before so I'll need guidance.

**Comment by peterjc** [comment]
Thanks for reporting this - you would need to change the URL here: https://github.com/biopython/biopython.github.io/blob/master/wiki/Active_projects.md

**Comment by Logan1x** [comment]
@peterjc pr created. Please review it :)

**Comment by jvfe** [comment]
PR #166 closes this issue, @peterjc

**Comment by peterjc** [comment]
Thank you, yes I should have closed it last week.
