### ISSUE TITLE
Fix old Interwiki links, e.g. bp: --> BioPerl.org wiki

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#17]
Most are linking to file format pages (which may no longer exist on the new bioperl.org), simplest solution is to do it manually after the final re-import from MediaWiki.

**Comment by vincentdavis** [comment]
I think this might me be a partial list of broken internal links of this type.

[bad internal wiki links.zip](https://github.com/biopython/biopython.github.io/files/226886/bad.internal.wiki.links.zip)

**Comment by MarkusPiotrowski** [comment]
They still exist on the new BioPerl pages. You find them under [http://bioperl.org/formats/sequence_formats/](http://bioperl.org/formats/sequence_formats/)

**Comment by peterjc** [comment]
I was under the impression the BioPerl team had a spring clean during their migration, so perhaps not all the pages will be there - and the relative URLs could have changed. Note there is no ``wiki`` in that URL anymore.

**Comment by peterjc** [comment]
I think that's all the interwiki links fixed now, so I'm closing this. We'll catch any remaining broken URLs as part of linting all the links - see #19.
