### ISSUE TITLE
Extract Molecule information

### ISSUE THREAD

**Issue by Chokerino** [biopython/biopython.github.io#171]
Hello,

Is there any way to extract info/names of the molecules present for a pdb id except for the one explicitly mentioned as entities? For example for [4u0g](https://www.rcsb.org/structure/4U0G) is shows various small molecules but they are not so easy to extract from the pdb.

**Comment by peterjc** [comment]
This is not a problem with the website - could you ask on https://github.com/biopython/biopython/issues instead please.
