### ISSUE TITLE
Do you support ClustalOmega in Biopython ?

### ISSUE THREAD

**Issue by ASQWZXED** [biopython/biopython.github.io#177]
Hello,
I haven't installed Biopython yet. I have two questions about it.
1- Does Biopython support ClustalOmega ? If yes,  can I align a data that is 5.5 MB on my regular PC using it?
2- When I have already aligned MSA data, can I convert it to SNP profiles using Biopython?

Thank you.

**Comment by peterjc** [comment]
This repository and issue tracker are intended for our website, https://github.com/biopython/biopython is the code itself.

As to Q1, yes we have a wrapper to help invoke ClustalOmega, and support for parsing the Clustal format alignments it generates in ``Bio.AlignIO`` under the format name ``"clustal"``

https://biopython.org/docs/dev/api/Bio.Align.Applications.html#Bio.Align.Applications.ClustalOmegaCommandline
https://biopython.org/docs/dev/api/Bio.AlignIO.html
https://biopython.org/wiki/AlignIO

As to Q2, I don't know what exactly you want. I suggest you ask on our mailing list https://biopython.org/wiki/Mailing_lists or the main repository, and please give more details such as a link to the desired output format, or a small example.
