### ISSUE TITLE
BioSQL wiki needs updates for Python 3

### ISSUE THREAD

**Issue by dapetillo** [biopython/biopython.github.io#183]
For a personal project that I am developing using Python 3.6, I was following instructions on [Managing local biological databases with the BioSQL module](http://biopython.org/wiki/BioSQL).

I noticed that some commands/instructions are not updated or simply not working with new Linux distros and python versions.

Few examples:
- `sudo apt install python-mysqldb` gives `no installation candidate` for Ubuntu 20.04 (but it works with `python3-mysqldb`)
- The [link to download the BioSQL schema](http://www.biosql.org/wiki/Downloads) is really old (August 2008). With recent versions of MySQL the schema import fails, and the official repo of BioSQL should be used instead.

I guess the problem is that the doc refers to Python 2 which is not supported anymore. Maybe the documentation should also show options on how to deal with BioSQL in Biopython using Python 3. 

If you agree, I am happy to update this part of the documentation.

**Comment by peterjc** [comment]
The Ubuntu change makes sense, pull request welcome.

The link https://biosql.org/wiki/Downloads is current, please upvote https://github.com/biosql/biosql/issues/21 about another release.

Python 2/3 updates are also welcome.

**Comment by peterjc** [comment]
Thanks for working on this. Can you see anything else which needs updating on this page?

**Comment by dapetillo** [comment]
Sure! For now I don't see anything else. If I do in the future, I will open a new issue/send pull requests.
