### ISSUE TITLE
Bio.PDB.DSSP 

### ISSUE THREAD

**Issue by wk989898** [biopython/biopython.github.io#191]
https://biopython.org/docs/1.76/api/Bio.PDB.DSSP.html
The dssp data returned for a single residue is not same with Biopython.
see # https://github.com/biopython/biopython/blob/94f3610609fc29f4ebce0d24d0d6a9d5ceef02d6/Bio/PDB/DSSP.py#L299

**Comment by JoaoRodrigues** [comment]
Could you provide us with additional details? For example, an example case
we can run and verify that indeed, the results differ between DSSP and
Biopython?

**Comment by wk989898** [comment]
Sorry,the issue is the order of dssp data doesn't match the description.
dssp_index should be the fourth element,not first.

**Comment by wk989898** [comment]
So sorry, I make a mistake. I use `dssp_dict_from_pdb_file` function and get dssp_dict. Thanks~
