### ISSUE TITLE
News feed page is not displayed properly

### ISSUE THREAD

**Issue by Saksham093** [biopython/biopython.github.io#193]
Hello, I was walking through [https://biopython.org/](https://biopython.org/) website, and the first link (i.e. [http://www.open-bio.org/category/biopython/feed/rss)](http://www.open-bio.org/category/biopython/feed/rss)) is not displayed properly.

![](https://user-images.githubusercontent.com/69385787/215513561-db2f9fa2-8f40-49fe-ac7e-b59845687ed1.png)

Something like this .... is this what expected to have or not ?

And I could like to contribute here.

**Comment by Saksham093** [comment]
I think the website link could be [https://www.open-bio.org/category/biopython/](https://www.open-bio.org/category/biopython/) ... Can I change this to doc ?

**Comment by peterjc** [comment]
That is working correctly, giving an RSS feed which is an XML file. However, while some browsers used to handle this natively (Firefox for example), but right now I get:

* Chrome, shows raw XML
* Firefox, downloads the XML with .rss extension
* Safari, prompts "This is a link to an RSS feed. Would you like to search the App Store for apps that can display RSS feeds?"

Given that news readers software using the RSS and Atom formats has (sadly) become less popular, perhaps you're right and we should just link to the human readable HTML instead. From there anyone looking for the RSS/Atom feed should be able to find it easily.

**Comment by Saksham093** [comment]
Ya, I got it. Thank You. But Can I link this to HTML where I convert this RSS Feed to Beautified HTML Page?

I want to give it a try.

**Comment by peterjc** [comment]
All I meant was e3fd10a3fa0d790128ce3a363bdb0d387dddcc7b - Thank you for spotting this and suggesting the improvement.
