### ISSUE TITLE
Mapping MediaWiki usernames to GitHub

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#2]
As of the last migration, these are the commit counts of the un-mapped usernames from the old biopython.org MediaWiki instance:

```
1 - Amitjoshi
1 - Daniel P.
1 - Dj winter
3 - Einar
1 - Emeryl
1 - Hugog
1 - James Estevez
1 - Jbbrown
1 - Jflatow
1 - Jtriley
1 - Kian.ho
1 - Kmcallenberg
1 - Konrad
2 - Krishna
1 - Marc Juul
3 - MatatTHC
2 - Matsen
1 - Mys 721tx
2 - Mzapala
2 - NeilenMarais
3 - Newacct
2 - Nfdelane
1 - Nuin
1 - Robschia
1 - Zach Stednick
```

You can see where I have mapped a username via https://github.com/biopython/biopython.github.io/graphs/contributors - please report any false matches here (or email me if you prefer).

(*Note* - In the short term I am still tweaking the conversion and will re-run the MediaWiki to Markdown conversion again, so correcting usernames now is easy)

**Comment by peterjc** [comment]
e.g. @keithcallenberg Were you ``Kmcallenberg`` on the Biopython wiki? They made one contribution, fixing a typo in WindowSize on the ProtParam page back on Jan 27, 2011.

**Comment by peterjc** [comment]
@stedy were you ``Zach Stednick`` on the Biopython wiki? They made one contribution, fixing a typo in description on the SeqRecord page back on Aug 5, 2011.

**Comment by stedy** [comment]
Wow, yeah I was and had totally forgotten about that. Thanks!

**Comment by peterjc** [comment]
@stedy - great - I'll add you to the GitHub mapping as I'll be redoing the import at least once more while we fine tune the wiki migration.

**Comment by keithcallenberg** [comment]
Hi Peter, yes, that was me. Thanks!  --Keith

**Comment by peterjc** [comment]
Thanks - updated list now that more pages are being included (see #6):

```
1 - Daniel P.
1 - Dj winter
2 - Edward.Tao
3 - Einar
1 - Emeryl
1 - Hugog
1 - James Estevez
1 - Jarretinha
1 - Jbbrown
1 - Jflatow
1 - Jtriley
1 - Kian.ho
1 - Konrad
2 - Krishna
1 - Marc Juul
2 - MarcSaric
3 - MatatTHC
2 - Matsen
1 - Mys 721tx
2 - Mzapala
2 - NeilenMarais
3 - Newacct
2 - Nfdelane
1 - Nuin
1 - Robschia
1 - ShawnDouglas
```

**Comment by brandoninvergo** [comment]
I wrote the [PAML page](http://biopython.org/wiki/PAML) and the section on PAML in the tutorial, but I can't remember if I added it directly or by giving it to you or Eric to add.

**Comment by peterjc** [comment]
@brandoninvergo The PAML page changes are under your name but not currently linked to your GitHub https://github.com/biopython/biopython.github.io/commits/master/wiki/PAML.md

In the raw commit the author is listed as ``Brandon Invergo <brandon@brandoninvergo.com>`` which looks like it matches your GitHub profile - am I overlooking something trivial here like a typo?

**Comment by brandoninvergo** [comment]
@peterjc No, that info is correct.  I guess I removed that email address from the addresses associated with my Github account (though it was still on my public profile).  I've just re-added it, so maybe it will work now.

**Comment by peterjc** [comment]
@brandoninvergo That fixed it. Strange that the public profile email address does not have to be one of the registered emails used to match up commit ownership.

**Comment by peterjc** [comment]
Realised ``Dj winter`` was another account for @dwinter so I'll add that mapping for any repeat migration (just one edit).

**Comment by peterjc** [comment]
http://biopython.org/wiki/User:ShawnDouglas points at http://openwetware.org/wiki/User:ShawnDouglas which mentions http://biomod.net/ which is hosted on GitHub at https://github.com/sdouglas/biomod

I therefore assume @sdouglas on GitHub was  ``ShawnDouglas`` on the Biopython MediaWiki?

**Comment by peterjc** [comment]
@etal your commits were not matching up, e.g. https://github.com/biopython/biopython.github.io/commits/master/wiki/User:EricTalevich.md - I will replace update the mapping to use your Google email address next time.

**Comment by peterjc** [comment]
@Nuin are you the ``Nuin`` who made a small contribution to the Biopython wiki back in 2007 fixing a typo in PAUP in the SeqIO page? http://biopython.org/wiki/SeqIO

Converted file history here: https://github.com/biopython/biopython.github.io/commits/master/wiki/SeqIO.md

**Comment by peterjc** [comment]
I've just redone the import which slightly reduced the remaining unmapped usernames. At this point I don't think we'll need to repeat the import, so will probably close this issue after a week or so?

**Comment by nuin** [comment]
@peterjc It was probably me, thanks.

**Comment by peterjc** [comment]
@nuin - thanks, you appear as a contributor now: https://github.com/biopython/biopython.github.io/graphs/contributors

**Comment by peterjc** [comment]
Belatedly closing this issue - we're not going to redo the MediaWiki import again, but we did get most of the wiki contributors mapped to GitHub accounts.
