### ISSUE TITLE
New Folder for example data?

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#24]
Related to #19, there are some links to sequence files that don't work any longer. I don't know how many of such sequence files are actually used and how long they are. However, I would suggest to have local copies in an additional folder and refer to them.

**Comment by peterjc** [comment]
Any examples pointing at biopython.org/SRC/... can point at the main repository instead (raw file links), e.g. data files under https://github.com/biopython/biopython/tree/master/Doc/examples or the Tests folder. Linting the links (#19) will help here.

There are likely to be some website only examples (e.g. CookBook contributions) where perhaps yes, a folder on the website repository makes most sense.

**Comment by peterjc** [comment]
As part of fixing #31 I have now created the ``examples/`` folder suggested. We can use this for any other sample files not also being used in the main source code repository.
