### ISSUE TITLE
collapse sidebar?

### ISSUE THREAD

**Issue by smsaladi** [biopython/biopython.github.io#26]
I wonder whether it would be possible to collapse the sidebar as in the [Python 3 docs website](https://docs.python.org/3/library/tempfile.html). The sidebar takes up quite a bit of space right now. Low priority right now, but I thought I'd mention it.

**Comment by peterjc** [comment]
The current hyde theme does make things narrower as the window size is changed, and on my mobile puts the sidebar information as a header instead.

But yes, if other people also find the current sidebar takes up too much space this would be a neat option.

**Comment by MarkusPiotrowski** [comment]
I agree with @smsaladi that the actual sidebar is quite prominent, e.g. when I size the page to 1/2 of my 17'' laptop it looks like this:

![untitled-1](https://cloud.githubusercontent.com/assets/4503120/16358216/91fc1aae-3b0d-11e6-8b14-6049bae0bcca.png)

It uses more than 1/3 of the page. 

I have made everything a little bit smaller (sidebar width, fonts, etc.) which looks like this:

![untitled-2](https://cloud.githubusercontent.com/assets/4503120/16358248/6f196496-3b0e-11e6-88d0-8b22f6b38c0b.png)

You can test this styling temporarily at http://markuspiotrowski.github.io. Less sidebar, more content. If nobody complains, I will prepare a pull request later next week.

**Comment by peterjc** [comment]
The test site looks good - also tested on an iPhone.

**Comment by smsaladi** [comment]
I agree. I think this is better - also looks good on an Android (ZTE Zinger)

**Comment by peterjc** [comment]
Cherry-picked as 5bc8fccedb07406882dc971a77225260a0404b97 from @MarkusPiotrowski 's repository - thank you.

Can we close this @smsaladi, or would you still like to have the sidebar collapsible?

**Comment by smsaladi** [comment]
I think this is great!
