### ISSUE TITLE
Remove/redirect SVN and CSV pages

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython.github.io#28]
At this point it would be in the git history if anyone ever wanted to go back and look at it. Thoughts?
biopython.github.io/wiki/CVS.md

**Comment by peterjc** [comment]
See also #29, should it just become a redirection to the main source code page?

**Comment by vincentdavis** [comment]
"redirection to the main source code page?" Sure

**Comment by tiagoantao** [comment]
I would just remove them for good. Less maintenance in the future and I doubt there are real downsides to deleting those.

**Comment by peterjc** [comment]
Deliberately breaking a URL when we can make it point somewhere directly relevant seems wrong to me.

There may be a more elegant way to do that within the YAML header for the main source code page (saying it redirects from the old CVS and SVN pages etc), which would allow us to remove ``CVS.md`` and ``SVN.md`` (#29)?

**Comment by peterjc** [comment]
See https://github.com/jekyll/jekyll-redirect-from - We should be able to add multiple redirect from entries to ``SourceCode.md``, e.g.

```
redirect_from:
  - /wiki/SVN
  - /wiki/CVS
```

That would let us delete ``SVN.md`` and ``CVS.md`` without breaking the old URLs :)

But first we need to fix the redirects, see #36.
