### ISSUE TITLE
Remove SVN.md

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython.github.io#29]
This page is no longer relevant and the GitMigration.md covers the migration, not sure that is still necessary.
https://github.com/biopython/biopython.github.io/blob/master/wiki/SVN.md

https://github.com/biopython/biopython.github.io/blob/master/wiki/GitMigration.md

**Comment by peterjc** [comment]
Its already a stub describing why we never used SVN, could make it into a redirect to the source code page?

**Comment by peterjc** [comment]
I'm going to close this as a duplicate of #28 since we'll fix them both the same way.
