### ISSUE TITLE
Visual styling including equivalent of MediaWiki sidebar

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#3]
i.e. Make it pretty and functional.

The last version of MediaWiki's special page ``MediaWiki:Sidebar`` was just:

```
      <text xml:space="preserve" bytes="505">* navigation
** Biopython|mainpage
** Download|Downloads
** Mailing lists|Mailing lists
** Documentation|Documentation
** :Category:Cookbook|Cookbook
** News|News
** SourceCode|Source Code
** https://github.com/biopython/biopython/issues|New issue tracker
** http://redmine.open-bio.org/projects/biopython|Old issue tracker
** http://testing.open-bio.org/biopython/|Buildbot Tests
** participants|Participants
** scriptcentral|Script Central
** recentchanges-url|recentchanges
** randompage-url|randompage</text>
```

I think that boils down to easy access to:

* https://github.com/biopython/biopython.github.io/blob/master/wiki/Biopython.md
* https://github.com/biopython/biopython.github.io/blob/master/wiki/Download.md
* https://github.com/biopython/biopython.github.io/blob/master/wiki/Mailing_lists.md
* https://github.com/biopython/biopython.github.io/blob/master/wiki/Documentation.md
* https://github.com/biopython/biopython.github.io/blob/master/wiki/Category:Cookbook.md
* https://github.com/biopython/biopython.github.io/blob/master/wiki/News.md (if #4 fixed; link to OBF blog category otherwise)
* https://github.com/biopython/biopython.github.io/blob/master/wiki/SourceCode.md
* https://github.com/biopython/biopython/issues
* http://testing.open-bio.org/biopython/
* https://github.com/biopython/biopython.github.io/blob/master/wiki/Participants.md
* https://github.com/biopython/biopython.github.io/blob/master/wiki/Scriptcentral.md

**Comment by peterjc** [comment]
To help people wanting to browse the current rendering,

http://biopython.github.io/wiki/Biopython
http://biopython.github.io/wiki/Download
http://biopython.github.io/wiki/Mailing_lists
http://biopython.github.io/wiki/Documentation
http://biopython.github.io/wiki/Category:Cookbook
http://biopython.github.io/wiki/News (see #4)
http://biopython.github.io/wiki/SourceCode
http://biopython.github.io/wiki/Participants
http://biopython.github.io/wiki/Scriptcentral

**Comment by peterjc** [comment]
I've got something functional using the hyde theme up and running currently.
![screenshot 2016-04-11 17 26 06](https://cloud.githubusercontent.com/assets/63959/14434418/962a15c4-000a-11e6-9eb0-4586166cdf74.png)

**Comment by tiagoantao** [comment]
cool!

**Comment by peterjc** [comment]
Here I've reused the Biopython logo on a dark grey background which @widdowquinn prepared for the @Biopython twitter banner https://twitter.com/biopython
![screenshot 2016-04-11 18 02 05](https://cloud.githubusercontent.com/assets/63959/14435401/9b4dcd16-000f-11e6-87f8-94050df7288d.png)

Someone else may be able to prepare a transparent logo which looks good on a dark background (@widdowquinn or @markuspiotrowski maybe?), here I've just made the side bar use HTML color 10100F to match the image ;)

See temporary branch https://github.com/biopython/biopython.github.io/tree/hyde3 for details

**Comment by peterjc** [comment]
I can imagine variants like the logo bottom left with the text (plus the "Biopython" text) top right. But I will leave this kind of polishing till later (and we can solicit community input)

**Comment by MarkusPiotrowski** [comment]
Am 11.04.2016 um 19:04 schrieb Peter Cock:
>
> Here I've reused the Biopython logo on a dark grey background which 
> @widdowquinn <https://github.com/widdowquinn> prepared for the 
> @Biopython <https://github.com/Biopython> twitter banner 
> https://twitter.com/biopython
>
On Internet Explorer 11 and Firefox (both on Windows), the black 
Biopython logo doesn't look so nice, it's fully blown up and thus blurred.


> screenshot 2016-04-11 18 02 05 
> <https://cloud.githubusercontent.com/assets/63959/14435401/9b4dcd16-000f-11e6-87f8-94050df7288d.png>
>
> Someone else may be able to prepare a transparent logo which looks 
> good on a dark background (@widdowquinn 
> <https://github.com/widdowquinn> or @markuspiotrowski 
> <https://github.com/markuspiotrowski> maybe?), here I've just made the 
> side bar use HTML color 10100F to match the image ;)
>
> See temporary branch 
> https://github.com/biopython/biopython.github.io/tree/hyde3 for details
>

Can you try the transparent Biopython.png from my Github.io pages (in 
folder images)?

Markus

**Comment by peterjc** [comment]
@MarkusPiotrowski you should be able to take a screenshot, save it to disk, and then drag it into the GitHub comment compose window.

Mac OS X Safari and Chrome looked fine (I can try Mac Firefox tomorrow), also iOS Safari looked good (the navigation is shown as a block at the top of each page, the same as if you make your window very narrow on the desktop).

**Comment by MarkusPiotrowski** [comment]
@peterjc I was talking about the Twitter page and the black logo there. 
The biopython.github.io page is OK, on Firefox you can see that the logo 
black is slightly different, on IE 11 you can't.

Am 11.04.2016 um 23:06 schrieb Peter Cock:
>
> @MarkusPiotrowski <https://github.com/MarkusPiotrowski> you should be 
> able to take a screenshot, save it to disk, and then drag it into the 
> GitHub comment compose window.
>
> Mac OS X Safari and Chrome looked fine (I can try Mac Firefox 
> tomorrow), also iOS Safari looked good (the navigation is shown as a 
> block at the top of each page, the same as if you make your window 
> very narrow on the desktop).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/biopython/biopython.github.io/issues/3#issuecomment-208560555>
>

-- 
_________________________________
Dr. Markus Piotrowski
Privatdozent/Akademischer Rat
Lehrstuhl für Pflanzenphysiologie
ND 3/49
Universitätsstr. 150
44801 Bochum

Tel. xx49-(0)234-3224290
Fax. xx49-(0)234-3214187

http://www.ruhr-uni-bochum.de/pflaphy/Seiten_dt/PG_Piotrowski_d.html
http://homepage.ruhr-uni-bochum.de/Markus.Piotrowski/Index.html

**Comment by peterjc** [comment]
@MarkusPiotrowski Thanks for the clarification, yes, there are some artefacts on the dark grey background logo currently in use on Twitter which I cropped out when I shrunk it for the current website prototype. @widdowquinn is going to try to have another look at that for us, working from the highest resolution original we have - this file pre-crop:

https://github.com/biopython/biopython/commit/1fe2001703d3af4c0d2fe7bdbdfc5a72589697fc

i.e. Make a new dark background version for Twitter, and if possible transparent version(s) which looks good on both a pale/white and dark/black background which would be most useful for the new website.

**Comment by peterjc** [comment]
New images from @widdowquinn on https://github.com/biopython/biopython/pull/807 - thank you!

We might want to use them here rather than in the source code repository (in which case I can do some git magic rather than requiring you do a new pull request).

**Comment by widdowquinn** [comment]
No worries - I'd have put them in this repo, if I'd have thought.

**Comment by peterjc** [comment]
I'm going to mark this as close given the site is currently functional - thank all for the input so far.
