### ISSUE TITLE
wiki/Concatenate_nexus example gene links are dead.

### ISSUE THREAD

**Issue by vincentdavis** [biopython/biopython.github.io#31]
The links below are dead, need the files or new links.
```
Say we have NEXUS files for three genes,
[btCOI.nex](http://atavism.webs.com/btCOI.nex),[btCOII.nex](http://atavism.webs.com/btCOII.nex)
and [btITS.nex](http://atavism.webs.com/btITS.nex), containing
alignments:
```

**Comment by peterjc** [comment]
Those would be David Winter's pages... @dwinter do you still have those example NEXUS files? We could host them here instead.

**Comment by lennax** [comment]
I don't know what NEXUS files are supposed to look at, but I guess the snippets shown aren't full examples (I copied them into files and tested the code, but it doesn't work).

**Comment by dwinter** [comment]
Hi all, 

That was many computers ago -- can't imagine I'll be able to find them. 

I'm happy to create some replacements and get the wiki example back to a reproducible  state though

**Comment by peterjc** [comment]
Reading http://biopython.org/wiki/Concatenate_nexus aka https://github.com/biopython/biopython.github.io/blob/master/wiki/Concatenate_nexus.md it would be simple enough to make new NEXUS files with those (mock) alignments in them even without any other metadata. Try generating the alignments in code and calling ``Bio.AlignIO.write(...)`` or even just make three FASTA files and use ``Bio.AlignIO.convert(...)``? You might need to set the alphabet to generic DNA too.

**Comment by lennax** [comment]
@dwinter that would be great.
I have a [branch](https://github.com/lennax/biopython.github.io/tree/Concatenate_nexus/wiki) where I've made other edits to the page.

**Comment by peterjc** [comment]
@lennax those minor edits on your branch looked good to me, I've cherry-picked them as 2139dd0836251598dd3a70bb320cdea8b8df4be8 and 08dd145194de83f94acd63492d12cb629460159c
