### ISSUE TITLE
Redirections don't work on Firefox, Chrome, Opera?

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#36]
While working on "Create_an_article_to_this_category.md" and "Degenerated.md" I experienced that Firefox (Windows), Chrome (Android) and Opera (Android) don't recoginze these redirect pages as `html` but as `application/octet stream`, i.e. they want to download the page as file. The download is actually the rendered redirect site (not the target site).
With IE11 it works (which usually means that there is a problem with the html but IE doesn't care...)

I wonder if the "head-like" code here is the problem:
``` html
...
<div class="content container">
      <!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting…</title>
<link rel="canonical" href="/wiki/Sequence_Cleaner">
<meta http-equiv="refresh" content="0; url=/wiki/Sequence_Cleaner">
<h1>Redirecting…</h1>
<a href="/wiki/Sequence_Cleaner">Click here if you are not redirected.</a>
<script>location="/wiki/Sequence_Cleaner"</script>

    </div>

  </body>
</html>
```

**Comment by vincentdavis** [comment]
I just found this same issue on wiki/Iddo_Friedberg.md.
I see in the examples for redirects that maybe it needs to include "layout: redirected"
See example here.
https://superdevresources.com/redirects-jekyll-github-pages/

I made this change and submitted a pull request to see if this fixes it.
https://github.com/biopython/biopython.github.io/pull/37

**Comment by MarkusPiotrowski** [comment]
No, it seems that we are using the JekyllRedirectFrom plugin, but something is mis-configured. Obviously the plugin writes a something like a new html header within the body of the wiki layout. I don't know if this is valid html.

**Comment by peterjc** [comment]
Possibly related, https://github.com/jekyll/jekyll-redirect-from/issues/105

**Comment by peterjc** [comment]
Also related, https://github.com/jekyll/jekyll-redirect-from/issues/84

**Comment by peterjc** [comment]
With https://github.com/biopython/biopython.github.io/commit/c1078aa975f8d00a30033cfd692d9c5fd497305e I've fixed the problem with the extra header etc, which is think was probably caused by https://github.com/jekyll/jekyll-redirect-from/issues/105 or something similar (i.e. a bug in the ``jekyll-redirect-from`` plugin).

Now the redirection pages return something sensible:

```
$ curl http://biopython.org/wiki/Tree
<!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting…</title>
<link rel="canonical" href="/wiki/Phylo">
<meta http-equiv="refresh" content="0; url=/wiki/Phylo">
<h1>Redirecting…</h1>
<a href="/wiki/Phylo">Click here if you are not redirected.</a>
<script>location="/wiki/Phylo"</script>
```

However, we have a mime type problem giving ``application/octet-stream`` which means it fails HTML validation and probably is why Chrome, Safari, etc are still upset:


```
$ curl -v http://biopython.org/wiki/Tree
*   Trying 192.30.252.153...
* Connected to biopython.org (192.30.252.153) port 80 (#0)
> GET /wiki/Tree HTTP/1.1
> Host: biopython.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: GitHub.com
< Date: Sat, 23 Apr 2016 20:38:05 GMT
< Content-Type: application/octet-stream
< Content-Length: 296
< Last-Modified: Sat, 23 Apr 2016 20:35:12 GMT
< Access-Control-Allow-Origin: *
< Expires: Sat, 23 Apr 2016 20:48:05 GMT
< Cache-Control: max-age=600
< Accept-Ranges: bytes
< X-GitHub-Request-Id: 1FB9CD7A:5B2B:3B71CFBA:571BDD2D
< 
<!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting…</title>
<link rel="canonical" href="/wiki/Phylo">
<meta http-equiv="refresh" content="0; url=/wiki/Phylo">
<h1>Redirecting…</h1>
<a href="/wiki/Phylo">Click here if you are not redirected.</a>
<script>location="/wiki/Phylo"</script>
* Connection #0 to host biopython.org left intact
```

This is likely linked to the html extension less permalinks (not used in earlier versions of the migration), something related to https://github.com/jekyll/jekyll-redirect-from/issues/84 I think?

**Comment by peterjc** [comment]
Curiously switching to using ``redirect_from`` (in the destination page header) rather than ``redirect_to`` (in the source page header), I can get this to work. This would also allow us to remove the redundant source pages from the repository, which would make navigation/browsing easier.

**Comment by MarkusPiotrowski** [comment]
Great! I also tried `redirect_from` in the destination file, but failed. Can you merge `Degenerated_Codons.md` which is redirected from `Degenerated.md` for testing?

**Comment by peterjc** [comment]
@MarkusPiotrowski e.g. Right now http://peterjc.github.io/wiki/Degenerated --> http://peterjc.github.io/wiki/Degenerated_Codons using:

```
$ git show -- wiki/Degenerated_Codons.md wiki/Degenerated.md
commit 18a2716029e75e241898a3ad535457c1c1e2969d
Author: Peter Cock <p.j.a.cock@googlemail.com>
Date:   Sat Apr 23 21:46:20 2016 +0100

    Use redirect_from instead of redirect_to
    
    Note sure why, but this fixes the mimetype problem with the
    redirection pages, and also reduces the number of markdown
    files in the repository.

diff --git a/wiki/Degenerated.md b/wiki/Degenerated.md
deleted file mode 100644
index 6ba992e..0000000
--- a/wiki/Degenerated.md
+++ /dev/null
@@ -1,7 +0,0 @@
----
-title: Degenerated
-permalink: wiki/Degenerated
-redirect_to: /wiki/Degenerated_Codons
----
-
-You should automatically be redirected to [Degenerated Codons](/wiki/Degenerated_Codons)
diff --git a/wiki/Degenerated_Codons.md b/wiki/Degenerated_Codons.md
index 26f1dee..25a1adc 100644
--- a/wiki/Degenerated_Codons.md
+++ b/wiki/Degenerated_Codons.md
@@ -2,6 +2,8 @@
 title: Degenerated Codons
 permalink: wiki/Degenerated_Codons
 layout: wiki
+redirect_from:
+ - /wiki/Degenerated
 ---
 
 Problem
```

**Comment by MarkusPiotrowski** [comment]
Works!
