### ISSUE TITLE
Embedded RSS/Atom news feed

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#4]
Under MediaWiki we embedded the Biopython news from the main OBF blog on these two pages, first title only on the main page:

```
<rss>http://news.open-bio.org/news/category/obf-projects/biopython/feed/|charset=utf-8|short|data|max=4|date</rss>
```

https://github.com/biopython/biopython.github.io/blob/master/wiki/Biopython.mediawiki
https://github.com/biopython/biopython.github.io/blob/master/wiki/Biopython.md

and in full:

```
<rss>http://news.open-bio.org/news/category/obf-projects/biopython/feed/rdf|charset=utf-8|date|max=4</rss>
```

https://github.com/biopython/biopython.github.io/blob/master/wiki/News.mediawiki
https://github.com/biopython/biopython.github.io/blob/master/wiki/News.md

Can we do something similar via Jekyll - or do we simply replace these embedded feeds with links to the Biopython category instead? i.e. https://news.open-bio.org/category/obf-projects/biopython/

**Comment by MarkusPiotrowski** [comment]
While it seems very easy to make your own RSS feed with Jekyll, embedding an existing feed as in MediaWiki seems to be hard. I didn't find an easy/any solution. Thus I would go for putting a link to the news pages.

**Comment by peterjc** [comment]
Yes, given Jekyll is often used to write blogs, with the wide-spread page vs post convention, there is lots of information online about producing RSS/Atom feeds. I too hadn't seen anything the other way round yet.

**Comment by peterjc** [comment]
Broken news page RSS embedding removed in PR #60, see https://github.com/biopython/biopython.github.io/commit/764a54250ab9ee04753382e9834645b6ae467f2f
