### ISSUE TITLE
Active projects still points to bugzilla?

### ISSUE THREAD

**Issue by tiagoantao** [biopython/biopython.github.io#46]
I think this should point to github issues... Or be removed altogether as in github this is obvious

I will do the change if deemed OK.

**Comment by tiagoantao** [comment]
ping @peterjc

**Comment by vincentdavis** [comment]
The are many dead links to bugzilla, you can find them in the files uploaded to issue #32

**Comment by peterjc** [comment]
Dead links to bugzilla can probably be turned into working links against redmine (since they were all migrated), and in some cases they will point you at a GitHub issue if already opened. If not, it might be a good redmine issue to migrate to github by hand?

**Comment by peterjc** [comment]
Fixed in https://github.com/biopython/biopython.github.io/commit/e31928cd111ccfae92816ed22210f20f40f6c1b4 and other commits today should have fixed all the old bugzilla links.
