### ISSUE TITLE
Participants page

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#59]
http://biopython.org/wiki/Participants, https://github.com/biopython/biopython.github.io/blob/master/wiki/Participants.md

The title **Participants** is misleading, isn't it? I have understood that these were participants of the old Wiki pages. Am I correct? Or what is the criterion for this list? While most of the names are familiar to me, some others are not, so this couldn't be the core developers?

I'm actually working on the page.

**Comment by peterjc** [comment]
I always understood it to be contributors to Biopython as a whole (not just the wiki), with the template having a specific entry to describe their contributions to Biopython (which need not be code). We could think about changing the title to "Biopython Contributors" instead?

Separately but related to this, we have a handful of User:XXX wiki pages, which on the whole are very minimal. I would personally favour deprecating them, perhaps just by redirecting them all to http://biopython.org/wiki/Participants instead?

**Comment by MarkusPiotrowski** [comment]
I agree with redirecting the empty or minimal User:XXX pages. 

I just wonder about the compilation of the list, some people who have a significant impact according to https://github.com/biopython/biopython/graphs/contributors?from=1999-12-05&to=2016-04-28&type=a are not on the list (and vice versa?). ([I like this view](https://github.com/biopython/biopython/graphs/contributors?from=2013-05-14&to=2013-09-02&type=a)  ;-) )

**Comment by peterjc** [comment]
The wiki page was largely self entered (the GitHub blame view certainly supports this), and perhaps as a group we've not been proactive enough to encourage everyone. I've just fixed the link to the ``CONTRIB`` file since we don't have the http://biopython.org/SRC/ mirror any more, and added a link to the GitHub contributors graphs.

Perhaps it should also link to the new website contributors graph too? https://github.com/biopython/biopython.github.io/graphs/contributors

Also, if you want to make a pull request turning some of the ``User:XXX`` pages into redirects, that would be great. See e.g. https://github.com/biopython/biopython.github.io/commit/4d180a0491274681bef1b92d66193edec48ab3b0 for how to do this.

**Comment by MarkusPiotrowski** [comment]
I'm actually working on the page and have included a link to the GitHub contributors page. I also spend some time to update some of the contacts. I will also include the redirect_from


Von Samsung Mobile gesendet

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Peter Cock <notifications@github.com> </div><div>Datum:28.04.2016  17:13  (GMT+01:00) </div><div>An: "biopython/biopython.github.io" <biopython.github.io@noreply.github.com> </div><div>Cc: Markus Piotrowski <Markus.Piotrowski@ruhr-uni-bochum.de>, Author <author@noreply.github.com> </div><div>Betreff: Re: [biopython/biopython.github.io] Participants page (#59) </div><div>
</div>The wiki page was largely self entered (the GitHub blame view certainly supports this), and perhaps as a group we've not been proactive enough to encourage everyone. I've just fixed the link to the CONTRIB file since we don't have the http://biopython.org/SRC/ mirror any more, and added a link to the GitHub contributors graphs.

Perhaps it should also link to the new website contributors graph too? https://github.com/biopython/biopython.github.io/graphs/contributors

Also, if you want to make a pull request turning some of the User:XXX pages into redirects, that would be great. See e.g. 4d180a0 for how to do this.

**Comment by peterjc** [comment]
Great. Don't worry about merging my change, just send the PR when ready and I'll merge it.

**Comment by MarkusPiotrowski** [comment]
I will address the `User:XXX` pages separately. Many of these (approx. 10) have no links (within biopython.org) which direct to them. Many of these are not listed on the `Participancts` page, so redirecting them there wouln't make sense. So we probably should make a `User` page (or a subheader on the `Participants` page) to direct to them. 
Those without content I would simply delete (including possible links pointing to them) (or redirect if there is something to direct to).

**Comment by peterjc** [comment]
I've opened #61 for dealing with user pages, but am closing this after merging #60. Thank you!
