### ISSUE TITLE
Styling: Format of inline code

### ISSUE THREAD

**Issue by MarkusPiotrowski** [biopython/biopython.github.io#70]
1.  The gray background of inline code is very light (can hardly be seen on some laptops), but also the  size and form of the background is somewhat bulky.
2. Links within inline code cannot be distuinguished (unless hovering over them)

I propose a darker, but smaller and more rounded background, and links within inline code should keep their blue color to clearly mark them as links (non-linking inline code keeps red):

"Old" style:
-  With link:

![untitled-1](https://cloud.githubusercontent.com/assets/4503120/15092682/863414fa-1471-11e6-8d79-396f72b330e7.png)
-  Without link:

![untitled-1a](https://cloud.githubusercontent.com/assets/4503120/15092704/1e20fd3c-1472-11e6-889b-f658a113855d.png)

"New" style: 
-  With link:

![untitled-2](https://cloud.githubusercontent.com/assets/4503120/15092683/8c20caf2-1471-11e6-8e63-82f523ea89a6.png)
-  Without link:

![untitled-2a](https://cloud.githubusercontent.com/assets/4503120/15092708/318d5b04-1472-11e6-8be0-3bf382f71844.png)

If nobody complains, I will prepare the respective pull request next week.

**Comment by peterjc** [comment]
That sounds sensible - I'd also noticed the in-line code and links didn't work together so well.

**Comment by peterjc** [comment]
Closed via #73 and https://github.com/biopython/biopython.github.io/commit/0a32727f95bc50cd81300017fbce47433c5909c6 - thank you.
