### ISSUE TITLE
README.html should be in the same style as the rest of the site

### ISSUE THREAD

**Issue by mgudapak** [biopython/biopython.github.io#82]
it doesn't include the default layouts (as the rest of the pages) so it shows up as a bare HTML page with no site styles/theme.

**Comment by peterjc** [comment]
The primary goal of the README file is for https://github.com/biopython/biopython.github.io but I guess we could add the layout to make http://biopython.org/README look pretty...

**Comment by MarkusPiotrowski** [comment]
Alternatively, just change the link in `index.md` to https://github.com/biopython/biopython.github.io/blob/master/README.md, which will open the `README` file in the GitHub repository.
I think there is no other link to the `README` except in this temporary `index.md`.

**Comment by mgudapak** [comment]
Hi Marcus - would this approach help in the case of testing while
developing locally? That's the scenario that prompted me to make this
change as I'd change the file but it always pointed to the server's
generated copy so there was no way to verify it locally.



On Sun, May 22, 2016 at 4:13 PM, Markus Piotrowski <notifications@github.com

**Comment by peterjc** [comment]
Is there an easy way to tell Jekyll NOT to render ``/README.md`` into http://biopython.org/README.html in order to avoid this potential confusion?
