### ISSUE TITLE
Creating a Biopython favicon

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython.github.io#86]
We can try basing this on https://github.com/biopython/biopython.github.io/commit/f5f346375d78d86e65f2c4fc04c2394938eba5e7 but I suspect this will be a challenge due to the typical scale. Perhaps a tiny yellow snake is enough?

See also #25.

**Comment by MarkusPiotrowski** [comment]
What I have tried so far:

Just a 'translation' of Biopython:
![favicon2 ico_16x16](https://cloud.githubusercontent.com/assets/4503120/15456590/76db3320-2075-11e6-8c80-76f75ad8beea.png)

Trying something Biopython logo-like:
![favicon3 ico_16x16](https://cloud.githubusercontent.com/assets/4503120/15456593/7a134460-2075-11e6-82eb-421e80011886.png)

I'm not very satisfied with them... Looking forward to seeing other submissions,  maybe we should announce this on the mailing list?

**Comment by peterjc** [comment]
Good idea Markus, yes, please ask on the mailing lists (main and dev). Your text based example is clever, that could work.

Just FYI, here's BioJava's which is just a sample version of their logo:
- http://biojava.org/favicon.ico
- https://github.com/biojava/biojava.github.io/blob/master/favicon.ico

I couldn't see how BioPerl's is setup with GitHub Pages, probably my browser has cached this? https://github.com/bioperl/bioperl.github.io/issues/35

**Comment by kescobo** [comment]
Do you have vectorized or at least high resolution versions of the biopython logo? I might take a stab, but it would be nice to have some consistency.

**Comment by peterjc** [comment]
Sadly we do not have the original vector art, just a reasonably high resolution bitmap - see http://biopython.org/wiki/Logo and http://biopython.org/DIST/docs/images/biopython.jpg

**Comment by souravsingh** [comment]
Has this been fixed?

**Comment by peterjc** [comment]
No, but with the new logo it should be much easier - see also https://github.com/biopython/biopython.github.io/tree/master/assets/images

**Comment by LalitNM** [comment]
@peterjc I have a suggestion, actually two.
1. We can use the biopython logo as favicon.
favicon:
![bp](https://user-images.githubusercontent.com/63332774/98903493-ba7c1b00-24dd-11eb-8e05-9e9af123c19c.png)

2. A square logo with just one loop.
favicon:
![square](https://user-images.githubusercontent.com/63332774/98905202-041a3500-24e1-11eb-8fc2-8f8f92c3b94e.png)

what do you think about this?

**Comment by MarkusPiotrowski** [comment]
@LalitNM Since favicons are squares, version 1 would contain much white space and the snakes would be rather small. Version 2 looks nice. I checked it on https://realfavicongenerator.net/ and it will give a nice favicon at different sizes (e.g. 16x16, 32x32).

**Comment by LalitNM** [comment]
@MarkusPiotrowski, in my opinion, we should not make a white background (as given by the https://realfavicongenerator.net/). I can make a 32x32 image of version-2. This will result in a transparent background.

**Comment by MarkusPiotrowski** [comment]
I used realfavicongenerator to have an impression how the logo looks if it is scaled on different systems. I also think that it doesn't make a white background but keeps the background as it is. Actually, I just used the picture from above, maybe your original file has a white background? A transparent background looks ok on white and dark themes. On the other hand, a black background looks also nice and would fit our web page theme.
Just go on, and maybe you can propose different versions with different backgrounds.

**Comment by peterjc** [comment]
Transparent background? That would match the style of most of the favicons I can see right now in my Chrome browser tabs.

**Comment by LalitNM** [comment]
I tried 32x32 favicon (version-2) on chrome and firefox. This looks nice. Have a look and let me know if it can be further improved.
Dark theme on chrome:
![chrome-dark](https://user-images.githubusercontent.com/63332774/98931217-c084f280-2503-11eb-89a7-323f31f365bf.png)
Light theme on chrome:
![chrome-light](https://user-images.githubusercontent.com/63332774/98931478-15286d80-2504-11eb-8cd8-cffbf17cdc32.png)
Firefox:
![firefox](https://user-images.githubusercontent.com/63332774/98931179-b7942100-2503-11eb-995c-34df5d187438.png)

**Comment by JoaoRodrigues** [comment]
Looks good here on a dark Firefox theme. Good job!
