### ISSUE TITLE
Broken URL 

### ISSUE THREAD

**Issue by tseemann** [biopython/biopython.github.io#88]
http://biopython.org/wiki/Scriptcentral

=>

Name	GenomeDiagram
Author	Leighton Pritchard
===> URL	https://ics.hutton.ac.uk/software/tools/
Description	A genomic and biological sequence schematic drawing package. Creates publication-quality genome schematics in several vector and bitmap formats.

**Comment by MarkusPiotrowski** [comment]
For me the link works nicely

**Comment by peterjc** [comment]
The link https://ics.hutton.ac.uk/software/tools/ works for me too (which it should, being on the Hutton network).  Also http://www.downforeveryoneorjustme.com/ics.hutton.ac.uk/software/tools/ seems happy.

@tseemann does http vs https make any difference? Other than a security warning as it tries to switch to https, does http://143.234.127.82/software/tools/ work? If you can give any more details (e.g. ping output) then I'll pass this on to my colleagues who look after this web server.

**Comment by peterjc** [comment]
See also https://github.com/biopython/biopython.github.io/commit/ab1c9ec520e5c769902bb7bcfa919fe90b7fefff - clarifying that GenomeDiagram has been included with Biopython since release 1.50

**Comment by tseemann** [comment]
Hmm it seems to be working now. Must have been a transient issue. Sorry.

**Comment by peterjc** [comment]
No problem - best to check, so thank you!
