### ISSUE TITLE
is biopython.org gone for good?

### ISSUE THREAD

**Issue by cswarth** [biopython/biopython.github.io#9]
Looks like the webserver that was running on the biopython.org domain is gone.  

Is this intentional or an oversight?

```
$ telnet 192.30.252.154 80
Trying 192.30.252.154...
Connected to 192.30.252.154.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Wed, 13 Apr 2016 00:13:24 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 9116
Connection: close
ETag: "5519ee21-239c"
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
X-GitHub-Request-Id: 8C6B7443:4DC2:10AE0202:570D8F1E
```

**Comment by cswarth** [comment]
Nevermind, saw the twitter notice.
https://twitter.com/Biopython/status/719899201921015812

**Comment by peterjc** [comment]
Its seems if I do a force push to the master branch, the GitHub pages briefly go off line with a 404 error:

*"There isn't a GitHub Pages site here.*

*If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account."*

Hopefully we won't have any further reason to do a force push - that ought to be the last re-import of the old MediaWiki site.

**Comment by peterjc** [comment]
This morning's outage was more likely due to me forgetting the magic ``CNAME`` file when I re-did the import: https://github.com/biopython/biopython.github.io/commit/8f4efb82f197c0dcd9091f06a7b1e18b30e6f2b1
